"""Script and storyboard exporters."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Tuple
from xml.etree.ElementTree import Element, SubElement, tostring

from .config import ProjectBrief


def _as_list(value: Any) -> List[Any]:
    if isinstance(value, list):
        return value
    return []


def _safe_int(value: Any, fallback: int) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return fallback


def _extract_issue_title(issue: Dict[str, Any], issue_number: int) -> str:
    title = issue.get("title")
    if isinstance(title, str) and title.strip():
        return title.strip()
    return f"Issue {issue_number}"


def _iter_panels(panel_scripts: Dict[str, Any]) -> List[Tuple[int, int, int, Dict[str, Any]]]:
    issues = _as_list(panel_scripts.get("issues"))
    rows: List[Tuple[int, int, int, Dict[str, Any]]] = []
    for issue_index, issue in enumerate(issues, start=1):
        if not isinstance(issue, dict):
            continue
        issue_number = _safe_int(issue.get("issue_number"), issue_index)
        pages = _as_list(issue.get("pages"))
        for page_index, page in enumerate(pages, start=1):
            if not isinstance(page, dict):
                continue
            page_number = _safe_int(page.get("page_number"), page_index)
            for panel_index, panel in enumerate(_as_list(page.get("panels")), start=1):
                if not isinstance(panel, dict):
                    continue
                panel_number = _safe_int(panel.get("panel_number"), panel_index)
                rows.append((issue_number, page_number, panel_number, panel))
    return rows


def _collect_issue_titles(issue_arcs: Dict[str, Any]) -> Dict[int, str]:
    titles: Dict[int, str] = {}
    for issue_index, issue in enumerate(_as_list(issue_arcs.get("issues")), start=1):
        if not isinstance(issue, dict):
            continue
        issue_number = _safe_int(issue.get("issue_number"), issue_index)
        titles[issue_number] = _extract_issue_title(issue, issue_number)
    return titles


def _get_nested(value: Dict[str, Any], key: str) -> Dict[str, Any]:
    nested = value.get(key)
    if isinstance(nested, dict):
        return nested
    return {}


def _extract_series_description(brief: ProjectBrief) -> str:
    details = [brief.premise.strip()]
    if brief.genre.strip():
        details.append(f"Genre: {brief.genre.strip()}")
    if brief.tone.strip():
        details.append(f"Tone: {brief.tone.strip()}")
    return " | ".join(piece for piece in details if piece)


def save_fountain_script(
    project_payload: Dict[str, Any],
    brief: ProjectBrief,
    output_root: Path,
    slug: str,
) -> Path:
    """Export the panel scripts as a Fountain-compatible text file."""
    out = output_root / slug / "graphic_novel.fountain"
    out.parent.mkdir(parents=True, exist_ok=True)

    panel_scripts = project_payload.get("panel_scripts", {})
    issue_titles = _collect_issue_titles(project_payload.get("issue_arcs", {}))

    lines: List[str] = [
        f"Title: {brief.title}",
        "Credit: Generated by Graphic Novel AI Studio",
        "Author: Graphic Novel AI Studio",
        f"Source: {brief.target_audience}",
        "",
        _extract_series_description(brief),
        "",
    ]

    current_issue = None
    current_page = None
    for issue_number, page_number, panel_number, panel in _iter_panels(panel_scripts):
        if current_issue != issue_number:
            current_issue = issue_number
            issue_title = issue_titles.get(issue_number, f"Issue {issue_number}")
            lines.append(f"# ISSUE {issue_number}: {issue_title}")
            lines.append("")
            current_page = None
        if current_page != page_number:
            current_page = page_number
            lines.append(f"INT. ISSUE {issue_number} PAGE {page_number} - CONTINUOUS")
            lines.append("")
        description = str(panel.get("description", "")).strip()
        camera = str(panel.get("camera", "")).strip()
        heading = f"= Panel {panel_number}: {description}" if description else f"= Panel {panel_number}"
        if camera:
            heading += f" [{camera}]"
        lines.append(heading)

        for beat in _as_list(panel.get("dialogue")):
            if not isinstance(beat, dict):
                continue
            speaker = str(beat.get("speaker", "NARRATOR")).strip().upper() or "NARRATOR"
            line = str(beat.get("line", "")).strip()
            if not line:
                continue
            lines.append(speaker)
            lines.append(line)
            lines.append("")

        sfx = [str(piece).strip() for piece in _as_list(panel.get("sfx")) if str(piece).strip()]
        if sfx:
            lines.append(f"> SFX: {', '.join(sfx)} <")
            lines.append("")

    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return out


def _append_paragraph(content: Element, paragraph_type: str, text: str) -> None:
    paragraph = SubElement(content, "Paragraph", {"Type": paragraph_type})
    text_node = SubElement(paragraph, "Text")
    text_node.text = text


def save_fdx_script(
    project_payload: Dict[str, Any],
    brief: ProjectBrief,
    output_root: Path,
    slug: str,
) -> Path:
    """Export a Final Draft XML (FDX) style script."""
    out = output_root / slug / "graphic_novel.fdx"
    out.parent.mkdir(parents=True, exist_ok=True)

    panel_scripts = project_payload.get("panel_scripts", {})
    issue_titles = _collect_issue_titles(project_payload.get("issue_arcs", {}))

    root = Element(
        "FinalDraft",
        {
            "DocumentType": "Script",
            "Template": "No",
            "Version": "1",
        },
    )
    content = SubElement(root, "Content")
    _append_paragraph(content, "General", brief.title)
    _append_paragraph(content, "General", _extract_series_description(brief))

    current_issue = None
    current_page = None
    for issue_number, page_number, panel_number, panel in _iter_panels(panel_scripts):
        if current_issue != issue_number:
            current_issue = issue_number
            issue_title = issue_titles.get(issue_number, f"Issue {issue_number}")
            _append_paragraph(content, "Act", f"ISSUE {issue_number}: {issue_title}")
            current_page = None
        if current_page != page_number:
            current_page = page_number
            _append_paragraph(content, "Scene Heading", f"ISSUE {issue_number} - PAGE {page_number}")

        description = str(panel.get("description", "")).strip()
        camera = str(panel.get("camera", "")).strip()
        action_line = f"Panel {panel_number}: {description}" if description else f"Panel {panel_number}"
        if camera:
            action_line += f" (Camera: {camera})"
        _append_paragraph(content, "Action", action_line)

        for beat in _as_list(panel.get("dialogue")):
            if not isinstance(beat, dict):
                continue
            speaker = str(beat.get("speaker", "NARRATOR")).strip() or "NARRATOR"
            line = str(beat.get("line", "")).strip()
            if not line:
                continue
            _append_paragraph(content, "Character", speaker)
            _append_paragraph(content, "Dialogue", line)

        sfx = [str(piece).strip() for piece in _as_list(panel.get("sfx")) if str(piece).strip()]
        if sfx:
            _append_paragraph(content, "Action", f"SFX: {', '.join(sfx)}")

    xml_bytes = tostring(root, encoding="utf-8", xml_declaration=True)
    out.write_bytes(xml_bytes)
    return out


def _escape_pdf_text(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _write_simple_text_pdf(lines: List[str], path: Path, lines_per_page: int = 48) -> Path:
    if not lines:
        lines = ["Storyboard is empty."]

    chunks = [lines[index : index + lines_per_page] for index in range(0, len(lines), lines_per_page)]

    objects: Dict[int, bytes] = {}
    objects[1] = b"<< /Type /Catalog /Pages 2 0 R >>"
    objects[2] = b""
    objects[3] = b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"

    kids: List[str] = []
    next_obj = 4
    for page_lines in chunks:
        page_obj = next_obj
        content_obj = next_obj + 1
        next_obj += 2

        kids.append(f"{page_obj} 0 R")
        page_body = (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            f"/Resources << /Font << /F1 3 0 R >> >> /Contents {content_obj} 0 R >>"
        )
        objects[page_obj] = page_body.encode("utf-8")

        text_ops = ["BT", "/F1 10 Tf", "50 760 Td", "14 TL"]
        for line in page_lines:
            clean = _escape_pdf_text(line)
            text_ops.append(f"({clean}) Tj")
            text_ops.append("T*")
        text_ops.append("ET")
        stream = "\n".join(text_ops).encode("utf-8")
        content = b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"\nendstream"
        objects[content_obj] = content

    objects[2] = f"<< /Type /Pages /Kids [{' '.join(kids)}] /Count {len(kids)} >>".encode("utf-8")

    ordered_ids = sorted(objects)
    pdf = bytearray()
    pdf.extend(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")

    offsets: Dict[int, int] = {}
    for obj_id in ordered_ids:
        offsets[obj_id] = len(pdf)
        pdf.extend(f"{obj_id} 0 obj\n".encode("ascii"))
        pdf.extend(objects[obj_id])
        pdf.extend(b"\nendobj\n")

    xref_start = len(pdf)
    pdf.extend(f"xref\n0 {max(ordered_ids) + 1}\n".encode("ascii"))
    pdf.extend(b"0000000000 65535 f \n")
    for obj_id in range(1, max(ordered_ids) + 1):
        offset = offsets.get(obj_id, 0)
        pdf.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    pdf.extend(
        (
            "trailer\n"
            f"<< /Size {max(ordered_ids) + 1} /Root 1 0 R >>\n"
            "startxref\n"
            f"{xref_start}\n"
            "%%EOF\n"
        ).encode("ascii")
    )

    path.write_bytes(bytes(pdf))
    return path


def save_storyboard_pdf(
    project_payload: Dict[str, Any],
    brief: ProjectBrief,
    output_root: Path,
    slug: str,
    preview_manifest: Dict[str, str] | None = None,
) -> Path:
    """Export a lightweight storyboard PDF with panel-level details."""
    out = output_root / slug / "storyboard.pdf"
    out.parent.mkdir(parents=True, exist_ok=True)

    panel_scripts = project_payload.get("panel_scripts", {})
    issue_titles = _collect_issue_titles(project_payload.get("issue_arcs", {}))
    prompt_lookup: Dict[str, str] = {}

    art_pack = _get_nested(project_payload, "art_prompt_pack")
    for issue in _as_list(art_pack.get("issue_prompts")):
        if not isinstance(issue, dict):
            continue
        for panel in _as_list(issue.get("panel_prompts")):
            if not isinstance(panel, dict):
                continue
            location = str(panel.get("location", "")).strip()
            prompt = str(panel.get("prompt", "")).strip()
            if location and prompt:
                prompt_lookup[location] = prompt

    lines: List[str] = [
        f"{brief.title} - Storyboard",
        f"Premise: {brief.premise}",
        "",
    ]

    current_issue = None
    current_page = None
    for issue_number, page_number, panel_number, panel in _iter_panels(panel_scripts):
        if current_issue != issue_number:
            current_issue = issue_number
            current_page = None
            lines.append(f"Issue {issue_number}: {issue_titles.get(issue_number, f'Issue {issue_number}')}")
            lines.append("-" * 72)
        if current_page != page_number:
            current_page = page_number
            lines.append(f"Page {page_number}")

        location = f"Issue {issue_number} Page {page_number} Panel {panel_number}"
        lines.append(f"  Panel {panel_number}: {str(panel.get('description', '')).strip()}")
        camera = str(panel.get("camera", "")).strip()
        if camera:
            lines.append(f"    Camera: {camera}")

        dialogues = []
        for beat in _as_list(panel.get("dialogue")):
            if not isinstance(beat, dict):
                continue
            speaker = str(beat.get("speaker", "")).strip()
            line = str(beat.get("line", "")).strip()
            if speaker and line:
                dialogues.append(f"{speaker}: {line}")
        if dialogues:
            lines.append(f"    Dialogue: {' | '.join(dialogues)}")

        if location in prompt_lookup:
            lines.append(f"    Prompt: {prompt_lookup[location]}")
        if preview_manifest and location in preview_manifest:
            lines.append(f"    Preview: {preview_manifest[location]}")
        lines.append("")

    return _write_simple_text_pdf(lines, out)


